name: SILShack Spring 2014
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]

gems:
  - jemoji

timezone: America/New_York

special-categories: 
  - "exercise"
  - "how-to"

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - schedule
  - exercises
  - how-to
  - people
  - feedback
  - music

# Same note RE case above
python-extra-pages:
  - console
  
  
baseurl: /spring2014
url: /spring2014

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Spring 2014

authors:
  elliott:
      name: Elliott Hauser
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.  
  grant:
      name: Grant McLendon
      prof: true
      gravatar: eeb73c80c4450528bf5eac5f1dedae9e
      website: http://grantmclendon.com
      github: gerbal
      twitter: gerbal100
      about: Grant is a first year MSIS student. He's from Chapel Hil and like playing with new technologies and getting way in over his head.
  zbay:
      name: Zachary Williams
      prof: false
      gravatar: 
      website: http://zbay.github.io/spring2014/
      github: zbay
      twitter: 
      about:  Zach is a sophomore Information Science and Political Science double major at UNC. He hails from Fairfax, Virginia.
  Adrian:
      name: Adrian Ogletree
      prof: false
      gravatar: 46713fd106ce3203526cf52e9caa4c64
      github: aogletree
      twitter: oftheadriatic
      about: Adrian is a second year MSIS student. She is from Austin, Texas.
  katielmeyer:
      name: Katie Meyer
      prof: false
      gravatar: 1a03889fb33eb025aaf0f71fcde449ae
      website: http://www.katielmeyer.net
      github: katielmeyer
      twitter: katielmeyer
      about: Katie is a first year MSIS student from Raleigh NC. She's also a Web UI Developer at IBM.
  allen:
      name: Allen Lyons
      prof: false
      gravatar:
      website: http://www.unc.edu/~lyonsa/
      github: lyonsa
      twitter: lions8lyons
      about: Allen is a fourth year UNC undergraduate in the BSIS program. No idea what he is going to do after he graduates but hopefully he'll be doing something that makes money. Likes playing with new tech, watch tv and movies, reading comic books, playing video games, and spending time with his friends and family. Depending on the whole job thing he may also be consuming a considerable amount of alcohol this semester.
  bdferr:
      name: Brendan Ferreri-Hanberry
      prof: false
      gravatar:
      github: bdferr
      twitter:
      about: Brendan is an MSIS student from Virginia. In his free time, he writes articles about drug policy at ssdp.org/about/blog-contributors/brendan-ferreri-hanberry/ and at the-libertarian.co.uk, where he serves as an editor.
  tlchristian:
      name: Thu-Mai Christian
      prof: false
      github: tlchristian
      twitter: tl_christian
      about: Thu-Mai is a SILS PhD student and a data archivist at the Odum Institute. I will solve all of your data management problems.
  blucka12: 
      name: Oak Ritchie
      prof: false
      gravitar: 
      website: http://www.steadyflowblog.com
      github: blucka12
      twitter: oakritchie
      about: Oak is a first year MSIS student, and is learning.
  julie:
    name: Julie Seifert
    prof: false
    github: juliees39
    twitter: julieseifert
    about: Julie Seifert is a second year MSLS student. She is from Tampa, Florida and enjoys kayaking and other water sports.
  ethan:
      name: Ethan Kavanaugh
      prof: false 
      gravatar: 
      website: http://www.nooooooooooooooo.com/
      github: babykav
      twitter: ethankavanaugh
      about: Ethan is a senior BSIS student. Lover of bacon. Avid user of handrails. 
  dcowhig:
      name: David Cowhig
      prof: false
      gravatar: 
      website: http://www.unc.edu/~dcowhig
      github: dcowhig
      twitter:
      about: David is a student at the University of North Carolina. He is currently an Information Science (BSIS) major.
  haley:
      name: Haley Walton
      prof: false
      github: Gefionne
      twitter: hmwalts
      about: Haley is a second-year MSLS student. Librarian, equestrian, gamer.
  srmoore5:
    name: Sierra Moore
    prof: false
    website:
    github: srmoore5
    twitter:
    about: Sierra is a first year MSIS student
  agooch:
      name: Mandy Gooch
      prof: false
      gravatar:
      website: 
      github: agooch
      twitter: 
      about: Mandy is a second year MSLS student. She is from Virginia and has a background in Asian Studies. Currently she works as a Research Data Coordinator at The Odum Institute at UNC. 
  amanda:
      name: Amanda Holt
      prof:
      gravatar:
      website:
      github: holtam
      about: Amanda is a fourth year undergrad studying Information Science at UNC Chapel Hill.
  elizahinkes:
      name: Eliza Hinkes
      prof: false
      github: elizahinkes
      about: Eliza is a junior Information Science and History double major from Newton, NJ.
  laura:
      name: Laura Ashcraft
      prof: false
      gravatar:
      github: lasher09
      twitter: 
      about: Laura is a first year MLS student. She is from Long Beach, California. She likes learning new things.
  libbby:
      name: Libby Livingston
      prof: false
      gravatar:
      website:
      github: libbby
      twitter:
      about: Libby is a BSIS student in SILS. She double majors in Geography, and is working on a minor in Art History.
  xuxiang:
      name: Xuxiang Mao
      prof: false
      gravatar:
      github: maoxuxiang
      twitter:
      about: I am a first year MSIS student
  sunhwap:
      name: Sunhwa Park 
      prof: false
      gravatar:
      github: sunhwap
      twitter:
      about:
  brittany:
      name: Brittany Hayes
      prof: false
      gravatar:
      website:
      github: britth
      twitter:
      about: Brittany is a second year MSIS student. She is interested in information retrieval, data mining, and natural language processing.
  yonghao:
      name: Yonghao Yu
      prof: false
      gravator: 
      website:
      github: yonghaoy
      twitter: yonghao_yu
      about: yonghao is a second year graduate year of SILS student. He is from China.
  madeline:
      name: Madeline Coven
      prof: false
      gravatar:
      website:
      github: madeline13
      twitter:
      about: Madeline is a second-year MSIS student.  She enjoys data visualizations and information design.
  jacobthill:
      name: Jacob Hill
      prof: false
      gravatar:
      website:
      github: jacobthill
      twitter:
      about: Jacob is a second year PhD student. His research is in the area of digital humanities and Middle East studies.
  slaffer:
      name: Sophia Lafferty-Hess
      prof: false
      gravatar:
      website:
      github: slaffer
      twitter:
      about: Sophia is a third year dual-degree MSIS and Masters of Public Administration student.
  jtbeeker:
     name: Jeremy Beeker
     prof: false
     gravatar:
     website: http://www.unc.edu/~jtbeeker
     twitter:
     about: Jeremy is a junior undergraduate information science student at unc chapel hill. 
  jskaa:
     name: Jessica Feng
     prof: false
     gravatar:
     website:
     twitter:
     about: Jessica is a senior information science student at UNC.
  lei:
      name: Lei Wang
      prof: false
      gravator: 
      website:
      github: leiw414
      twitter: zuoyou414
      about: Lei Wang is a second year MSIS student. 
  chunxi:
      name: Chunxi Zhang
      prof: false
      gravator: 
      website:
      github: lanblue
      twitter: 
      about: Chunxi is a first year graduate year of SILS student. She is from China.
